### ISSUE TITLE
Automatizer can try to add class to nonexistent squelch rule, crashing the game

### ISSUE THREAD

**Issue by miramor** [tome2/tome2#22]
To reproduce:
1. (n) for new rule; it can be any type 
2. (d) to delete the rule
3. There are now no rules, but you're still in the rule editing panel. Hit (a) to add a clause.
4. Attempting to add a clause to the nonexistent rule will crash the game.

Backtrace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff69e4f5d in __GI_abort () at abort.c:90
#2  0x00007ffff738b095 in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7388c86 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7388cd1 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7388f14 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff73b2a67 in std::__throw_out_of_range_fmt(char const*, ...) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x0000555555a8c740 in std::vector<std::shared_ptr<squelch::Rule>, std::allocator<std::shared_ptr<squelch::Rule> > >::_M_range_check(unsigned long) const ()
#8  0x0000555555a8ba3d in std::vector<std::shared_ptr<squelch::Rule>, std::allocator<std::shared_ptr<squelch::Rule> > >::at(unsigned long) ()
#9  0x0000555555a8b31e in squelch::Automatizer::add_new_condition(std::function<std::shared_ptr<squelch::Condition> ()>) ()
#10 0x00005555559cb170 in do_cmd_automatizer() ()
#11 0x000055555586990e in do_cmd_options() ()
#12 0x0000555555881b75 in process_command() ()
#13 0x00005555558825fb in process_player() ()
#14 0x00005555558834b8 in dungeon() ()
#15 0x0000555555884063 in play_game ()
---Type <return> to continue, or q <return> to quit---
#16 0x000055555583b1ef in main_real ()
#17 0x000055555583ab27 in main ()
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff69e4f5d in __GI_abort () at abort.c:90
#2  0x00007ffff738b095 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7388c86 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7388cd1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7388f14 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff73b2a67 in std::__throw_out_of_range_fmt(char const*, ...) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x0000555555a8c740 in std::vector<std::shared_ptr<squelch::Rule>, std::allocator<std::shared_ptr<squelch::Rule> > >::_M_range_check(unsigned long) const ()
#8  0x0000555555a8ba3d in std::vector<std::shared_ptr<squelch::Rule>, std::allocator<std::shared_ptr<squelch::Rule> > >::at(unsigned long) ()
#9  0x0000555555a8b31e in squelch::Automatizer::add_new_condition(std::function<std::shared_ptr<squelch::Condition> ()>) ()
#10 0x00005555559cb170 in do_cmd_automatizer() ()
#11 0x000055555586990e in do_cmd_options() ()
#12 0x0000555555881b75 in process_command() ()
#13 0x00005555558825fb in process_player() ()
#14 0x00005555558834b8 in dungeon() ()
#15 0x0000555555884063 in play_game ()
#16 0x000055555583b1ef in main_real ()
#17 0x000055555583ab27 in main ()
```

I'll attempt to introduce a patch, as the cause seems pretty obvious; obvious answer is "make sure you're in the rule add/delete tab, not the editing tab, after deleting a rule." Watch this space. I suspect, though, that this will not the last Automatizer crash bug.

**Comment by miramor** [comment]
Ah, there's an added condition: no other existing rules in the Automatizer. Whoops. Automatizer correctly selects the next rule if there is another, but if there is not, it fixes on a nonexistent one. This is a 3-line fix.

**Comment by miramor** [comment]
Hmm let's also make things more resilient re: not adding to a nonexistent rule in the first place.

**Comment by miramor** [comment]
Whoops, I think the bug in the deletion part may have dated back to the Darkgod era...

**Comment by miramor** [comment]
Pull request filed :)

**Comment by BardurArantsson** [comment]
This was all addressed by your PR, right? If not, feel free to reopen.
