### ISSUE TITLE
Multiple segfaults

### ISSUE THREAD

**Issue by tzargoth** [tome2/tome2#39]
After building 'master' and 'next' branches successfully on my Ubuntu 18 system, I was able to run tome2-x11 and tome2-gcu, but both are plagued by segfaults, preventing consistent operation.  I rebuilt 'master' in debug mode by hacking the CMake file to add the flags (I don't really know what I am doing there, but it worked) and got 2 separate outputs from different points of operation.

Changes to CMakeLists.txt:
```
#
# C Compiler Flags
#
#SET(CMAKE_C_FLAGS           "${CMAKE_C_FLAGS} ${COMMON_COMPILER_FLAGS}")
#SET(CMAKE_C_FLAGS_RELEASE   "-O2")
#SET(CMAKE_C_FLAGS_DEBUG     "-O0 -g ${SANITIZER_FLAGS}")
SET(CMAKE_C_FLAGS     "-O0 -g ${SANITIZER_FLAGS}")

#
# C++ Compiler Flags
#
#SET(CMAKE_CXX_FLAGS         "${CMAKE_CXX_FLAGS} ${COMMON_COMPILER_FLAGS}")
#SET(CMAKE_CXX_FLAGS_RELEASE "-O2")
#SET(CMAKE_CXX_FLAGS_DEBUG   "-O0 -g ${SANITIZER_FLAGS} -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC")
SET(CMAKE_CXX_FLAGS   "-O0 -g ${SANITIZER_FLAGS} -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC")

```

1) when generating a character and file already exists, and selecting 'y':
```
/usr/include/c++/7/debug/vector:424:
Error: attempt to subscript container with out-of-bounds index 190, but container only holds 24 elements.

Objects involved in the operation:
sequence "this" @ 0x0x61d0000005f8 {
  type = std::__debug::vector<player_race, std::allocator<player_race> >;
}
```

2) after successfully generating a character and beginning in Bree, walk around to the left and the screen shifts:

```
==14522==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffe84aad228 at pc 0x5613b6b0c321 bp 0x7ffe84aad140 sp 0x7ffe84aad130
READ of size 8 at 0x7ffe84aad228 thread T0
    #0 0x5613b6b0c320 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::_M_swap(std::__shared_count<(__gnu_cxx::_Lock_policy)2>&) /usr/include/c++/7/bits/shared_ptr_base.h:712
    #1 0x5613b754dd1c in std::__shared_ptr<monster_race const, (__gnu_cxx::_Lock_policy)2>::__shared_ptr(std::__shared_ptr<monster_race const, (__gnu_cxx::_Lock_policy)2>&&) /usr/include/c++/7/bits/shared_ptr_base.h:1133
    #2 0x5613b754be8e in std::shared_ptr<monster_race const>::shared_ptr(std::shared_ptr<monster_race const>&&) /usr/include/c++/7/bits/shared_ptr.h:245
    #3 0x5613b754a003 in _FUN<std::shared_ptr<const monster_race> > /home/seth/dev/c/tome2/src/cave.cc:1251
    #4 0x5613b752f094 in map_info_layer3 /home/seth/dev/c/tome2/src/cave.cc:1088
    #5 0x5613b7531acb in map_info /home/seth/dev/c/tome2/src/cave.cc:1262
    #6 0x5613b7533656 in lite_spot(int, int) /home/seth/dev/c/tome2/src/cave.cc:1478
    #7 0x5613b701494e in update_mon(int, char) /home/seth/dev/c/tome2/src/monster2.cc:1760
    #8 0x5613b6fa27db in process_monster /home/seth/dev/c/tome2/src/melee2.cc:6125
    #9 0x5613b6fa7a36 in process_monsters() /home/seth/dev/c/tome2/src/melee2.cc:6517
    #10 0x5613b6bf59a8 in dungeon /home/seth/dev/c/tome2/src/dungeon.cc:4499
    #11 0x5613b6bf9021 in play_game /home/seth/dev/c/tome2/src/dungeon.cc:4846
    #12 0x5613b6a691b3 in main_real /home/seth/dev/c/tome2/src/main.cc:262
    #13 0x5613b6a67dc6 in main (/home/seth/dev/c/tome2/src/tome-x11+0x2154dc6)
    #14 0x7f3c5ad71b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #15 0x5613b6a645a9 in _start (/home/seth/dev/c/tome2/src/tome-x11+0x21515a9)

Address 0x7ffe84aad228 is located in stack of thread T0 at offset 40 in frame
    #0 0x5613b7549f22 in _FUN<std::shared_ptr<const monster_race> > /home/seth/dev/c/tome2/src/cave.cc:1246

  This frame has 2 object(s):
    [32, 40) '<unknown>' <== Memory access at offset 40 overflows this variable
    [96, 112) '<unknown>'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /usr/include/c++/7/bits/shared_ptr_base.h:712 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::_M_swap(std::__shared_count<(__gnu_cxx::_Lock_policy)2>&)
Shadow bytes around the buggy address:
  0x10005094d9f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005094da00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005094da10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005094da20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005094da30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10005094da40: f1 f1 f1 f1 00[f2]f2 f2 f2 f2 f2 f2 00 00 f2 f2
  0x10005094da50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005094da60: 00 00 f1 f1 f1 f1 01 f2 f2 f2 f2 f2 f2 f2 01 f2
  0x10005094da70: f2 f2 f2 f2 f2 f2 02 f2 f2 f2 f2 f2 f2 f2 02 f2
  0x10005094da80: f2 f2 f2 f2 f2 f2 00 00 f2 f2 f2 f2 f2 f2 00 00
  0x10005094da90: f2 f2 f2 f2 f2 f2 00 00 f2 f2 f2 f2 f2 f2 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==14522==ABORTING

```

Compiled using: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

I can consistently get it to segfault walking around Bree.  If another dump will be useful, I can get more.

**Comment by cizra** [comment]
Bisecting shows that the crashes got introduced at:
bfa9713ee6e8299cb6cd26dd291b024191926070
De-duplicate code in map_info{,_default}

**Comment by jkatzmewing** [comment]
This sounds like the same crashes I found? If so they won't occur when compiled with Clang 8.x.
