### ISSUE TITLE
intermittent map_info_layer1 crash, apparently associated with color processing

### ISSUE THREAD

**Issue by jkatzmewing** [tome2/tome2#58]
I accidentally saved my game right before an intermittent crash, so the save file crashes dependably on loading.

This is on an AMD Ryzen 5000 series desktop, running Fedora 34 (Gnome/Wayland).

A link to the save file on my Nextcloud: https://hottestgirlinthe.club/s/fLX7BwoaPCt6abp

Crash output:

```
% ./tome-x11 
/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/debug/vector:445:
In function:
    std::vector::const_reference 
    std::vector<effect_type>::operator[](std::vector::size_type) const [_Tp 
    = effect_type, _Allocator = std::allocator<effect_type>]

Error: attempt to subscript container with out-of-bounds index 10, but 
container only holds 10 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x61d000000930 {
      type = std::__debug::vector<effect_type, std::allocator<effect_type> >;
    }
zsh: IOT instruction (core dumped)  ./tome-x11
```

GDB backtrace:

```
#0  0x00007ffff78fb2a2 in raise () from /lib64/libc.so.6
#1  0x00007ffff78e48a4 in abort () from /lib64/libc.so.6
#2  0x00007ffff7b811d5 in __gnu_debug::_Error_formatter::_M_error() const [clone .cold] () from /lib64/libstdc++.so.6
#3  0x0000000001b12fae in std::__debug::vector<effect_type, std::allocator<effect_type> >::operator[] (this=0x61d000000930, __n=10)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/debug/vector:445
#4  0x0000000001adf3cd in map_info_layer1 (c_ptr=0x62800005c568, apply_effects=true, 
    feature_fn=0x1b0f240 <map_info(int, int, unsigned char*, char*)::$_0::__invoke<feature_type const*>(feature_type const*)>, 
    store_fn=0x1b0f380 <map_info(int, int, unsigned char*, char*)::$_1::__invoke<store_info_type const*>(store_info_type const*)>, cp=0x7fffffffbe10 "#\003", 
    ap=0x7fffffffbe00 "\005\276\377\377\377\177") at src/cave.cc:936
#5  0x0000000001ae7eaa in map_info (y=18, x=14, ap=0x7fffffffbe00 "\005\276\377\377\377\177", cp=0x7fffffffbe10 "#\003") at src/cave.cc:1305
#6  0x0000000001b103d9 in prt_map()::$_8::operator()() const (this=0x7fffffffc1a0) at src/cave.cc:1562
#7  0x0000000001b100ac in std::__invoke_impl<void, prt_map()::$_8&>(std::__invoke_other, prt_map()::$_8&) (__f=...)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
#8  0x0000000001b0ff7c in std::__invoke_r<void, prt_map()::$_8&>(prt_map()::$_8&) (__fn=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
#9  0x0000000001b0fbbe in std::_Function_handler<void (), prt_map()::$_8>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:291
#10 0x0000000000c9dd3a in std::function<void ()>::operator()() const (this=0x7fffffffc1a0)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:560
#11 0x0000000001aa7685 in Term_with_saved_cursor_visbility(std::function<void ()>) (callback=...) at src/z-term.cc:1450
#12 0x0000000001ae81bc in prt_map () at src/cave.cc:1549
#13 0x000000000199fd25 in redraw_stuff () at src/xtra1.cc:4092
#14 0x0000000000c4269b in dungeon () at src/dungeon.cc:4305
#15 0x0000000000c3a73c in play_game (args=...) at src/dungeon.cc:4781
#16 0x0000000000a3147a in main_real (argc=1, argv=0x7fffffffdf98, platform_sys=0x1edbbc0 <str> "x11", init_platform=0xa11f40 <init_x11(int, char**)>, 
    platform_usage=0x1edbc00 <str> "  -- -n#", ' ' <repeats 13 times>, "Number of terms to use\n  -- -d<name>        Display to use\n") at src/main.cc:280
#17 0x0000000000a1cf48 in main (argc=1, argv=0x7fffffffdf98) at src/main-x11.cc:1765
```

And what appears to be the affected code area, around cave.cc:936:

```
              /**** Step 2 -- Apply special random effects ****/
                if (apply_effects)
                {
                        /* Special terrain effect */
                        if (auto effect_idx = c_ptr->maybe_effect)
                        {
                                a = spell_color(lasting_effects[*effect_idx].type);
                        }

                        /* Multi-hued attr */
                        else if (f_ptr->flags & FF_ATTR_MULTI)
                        {
                                a = f_ptr->shimmer[rand_int(7)];
                        }
                }
```

**Comment by jkatzmewing** [comment]
I can confirm that Piotr's fixes work FYI.
